src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

src/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

src/shop/models/category.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.id])

src/shop/models/product.py
from django.db import models
from django.urls import reverse

from .category import Category


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

src/shop/views.py
from django.shortcuts import render, get_object_or_404

from shop.models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    

    template_name = 'shop/product/list.html'
    context = {'category': category,
                'categories': categories,
                'products': products}

    return render(request, template_name, context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, is_available=True)

    cart_product_form = CartAddProductForm()

    template_name = 'shop/product/detail.html'
    context = {'product': product,
                'cart_product_form': cart_product_form}

    return render(request, template_name, context)

src/shop/templates/shop/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button class="close" type="button" name="button" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

src/shop/templates/shop/partials/_css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/admin.css' %}">
<!-- links add here -->
<!-- <link rel="stylesheet" href="{% static '' %}"> -->

<!-- links add here -->
<link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Custom styles goes to this files -->

src/shop/templates/shop/partials/_javascripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/' %}"></script>
<!-- links add here -->
<script type="text/javascript" src="{% static 'js/' %}"></script>

<!-- links add here -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

src/shop/templates/shop/partials/_pagination.html
<div class="row">
  <div class="col-md-12">
    {% if context_key.has_other_pages %}
      <ul class="pagination">
        {% if context_key.has_previous %}
          <li class="page-item" >
            <a href="?page={{ context_key.previous_page_number }}" class="page-link">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link">&laquo;</a>
          </li>
        {% endif %}
        {% for i in context_key.paginator.page_range %}
          {% if context_key.number == i %}
            <li class="page-item active" >
              <a class ="page-link">{{ i }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a href="?page={{i}}" class="page-link">{{ i }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if context_key.has_next %}
          <li class="page-item" >
            <a href="?page={{ context_key.next_page_number }}" class="page-link">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
</div>
</div>
</section>

src/shop/templates/shop/partials/_sidebar.html
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li 
        {% if not category %}
            class="selected"
        {% endif %}
            >
            <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        
        {% for c in categories %}
            <li 
            {% if category.slug == c.slug %}
                class="selected"
            {% endif %}
                >
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
            
    </ul>
</div>

src/shop/templates/shop/partials/_topbar.html
<div id="header">
    <a href="/" class="logo">E-Mart</a>
</div>

<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }}
                    ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
</div>